### ISSUE TITLE
No rollbacks in session.executeLambda

### ISSUE THREAD

**Issue by KotoJallow** [aws-samples/amazon-qldb-dmv-sample-nodejs#2]
Transactional base executions via session.executeLambda does not `rollback` when an error occurs within the transaction. I wrote a wrong query within a transaction and got the BadRequestException error that's fine but mutations within that transaction were successfully executed. No rollbacks.

**Comment by saumehta9** [comment]
Hi @KotoJallow , 

It appears that the issue already got addressed [here](https://github.com/awslabs/amazon-qldb-driver-nodejs/issues/11).

Marking this as closed. Please feel free to reopen for more help.
